name: Python build and test

on: [push]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: ruff
        uses: chartboost/ruff-action@v1

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Gurobi License
        shell: bash
        env:
          WLSLICENSE: ${{ secrets.WLSLICENSE }}
        run: |
          echo "$WLSLICENSE" > $HOME/gurobi.lic
      - name: Install Hatch
        uses: pypa/hatch@install
      - name: Run tests
        run: hatch run dev:pytest -s tests/
      # - name: Build dist
      #   run: hatch build
      # - name: Publish on PyPI
      #   if: github.ref == 'refs/heads/main'
      #   run: hatch publish
