name: Python build and test

on: [push]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: ruff
        uses: chartboost/ruff-action@v1

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Install OpenBLAS (needed for SCS)
        run: sudo apt-get update && sudo apt-get install -y libopenblas-dev

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up uv
        # Install a specific uv version using the installer
        run: curl -LsSf https://astral.sh/uv/0.4.1/install.sh | sh

      # TODO (bart): we need to set up the correct WLS license for this
      # - name: Install Gurobi License
      #   shell: bash
      #   env:
      #     WLSLICENSE: ${{ secrets.WLSLICENSE }}
      #   run: |
      #     echo "$WLSLICENSE" > $HOME/gurobi.lic

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run tests
        # For example, using `pytest`
        run: uv run pytest tests
